bcgov/invasivesBC-mussels-iOS

ipad.xcodeproj/project.pbxproj, ipad/Utilities/API/AppRemoteAPIConst.swift, ipad/Utilities/API/RemoteAPI.swift, ipad/Utilities/API/RemoteAPIManager.swift, ipad/Utilities/GenericCore/GenericConst.swift, ipadTests/RemoteAPITest.swift
=> Ins-833-875

ipad/Database/Storage.swift, ipad/Shared Components/Form/Input Cells/InputItem.swift, ipad/Utilities/API/APIRequest.swift, ipad/Utilities/API/Code Tables/CodeTables.swift, ipad/Utilities/API/Models/CodeTableModel.swift, ipad/Utilities/Dropdown Helper/DropdownHelper.swift, ipad/ViewControllers/Shift/Fields Generator/WatercraftInspectionFormHelper.swift
-------------------
1. Code table structure for new drop down
2. Handling code object within DropDown
-------------------------
=> New DropDown Codes

Podfile, ipad.xcodeproj/project.pbxproj, ipad/AppDelegate.swift, ipad/Constants/KeycloakConstants.swift, ipad/GoogleService-Info.plist, ipad/Utilities/API/APIRequest.swift, ipad/Utilities/APICore/AppRemoteAPIConst.swift, ipad/Utilities/GenericCore/FoundationExtension.swift, ipad/ViewControllers/Base.lproj/Main.storyboard, ipad/ViewControllers/HomeViewController.swift, ipadTests/UploadAPITest.swift, ipadTests/WatercraftRiskAssessment.swift, ipadTests/WorkflowAPITest.swift, ipadTests/testShift.swift
Integrate Crashlytics 
1. Update Pod
2. Update AppDelegate
=> INS-1054: Crash Log Framework Integration

ipad/Database/Storage.swift, ipad/Shared Components/Form/Input Cells/InputItem.swift, ipad/Utilities/API/Code Tables/CodeTables.swift, ipad/Utilities/API/Models/CodeTableModel.swift, ipad/Utilities/Dropdown Helper/DropdownHelper.swift, ipad/ViewControllers/Shift/Fields Generator/WatercraftInspectionFormHelper.swift, ipad/ViewControllers/Shift/Model/WatercraftInspectionModel.swift, ipad/ViewControllers/Shift/WatercraftInspectionViewController.swift
=> Update Model And CodeTable Model to support CountryProvince Remote Model

ipad.xcodeproj/project.pbxproj, ipad/Constants/KeycloakConstants.swift, ipad/Utilities/APICore/AppRemoteAPIConst.swift, ipad/Utilities/GenericCore/UIViewControllerExtensions.swift, ipad/ViewControllers/HomeViewController.swift
------------------
Finish API integration #296
----
=> Report Issue: #296

ipad/Constants/AppRemoteAPIConst.swift, ipad/Constants/KeycloakConstants.swift
------------
1. Create env enum and RemoteURLManager
2. Managing kc url and api url through env
-----------------------------
=> Issue #361

ipad/Models/Waterfract Inspection/WatercraftInspectionModel.swift
=> Task #411: Sending 'numberOfPeopleInParty' field data of inspection

ipad/Constants/StringConstants.swift, ipad/Models/Waterfract Inspection/Form Fields/WatercraftInspectionFormHelper.swift, ipad/Models/Waterfract Inspection/WatercraftInspectionModel.swift, ipad/ViewControllers/Watercraft Inspections/WatercraftInspectionViewController.swift
(Finish #393)
----------------------------------------
1. Add new radio switch for new passport issues.
2. Handle actions
-----------------
=> Implement #393: New Passport Issue Field

ipad.xcodeproj/project.pbxproj, ipad/Database/Storage.swift, ipad/Models/Waterfract Inspection/WatercraftInspectionModel.swift, ipad/ViewControllers/Watercraft Inspections/Cells/Destination Major City/DestinationMajorCityCollectionViewCell.swift, ipad/ViewControllers/Watercraft Inspections/Cells/Destination Major City/DestinationMajorCityCollectionViewCell.xib, ipad/ViewControllers/Watercraft Inspections/Cells/Previous Major City/PreviousMajorCityCollectionViewCell.swift, ipad/ViewControllers/Watercraft Inspections/Cells/Previous Major City/PreviousMajorCityCollectionViewCell.xib, ipad/ViewControllers/Watercraft Inspections/WatercraftInspectionViewController.swift, ipad/Views/Waterbody picker/Cells/WaterbodyTableViewCell.swift
Added row for major city when user selects a city
=> Add major city table row upon selection

ipad/Models/Waterfract Inspection/Form Fields/WatercraftInspectionFormHelper.swift, ipad/Models/Waterfract Inspection/PreviousWaterBodyModel.swift, ipad/Views/Waterbody picker/Cells/SelectedWaterBodyCollectionViewCell.swift
Fixed crashes related to invalid db models being sent back and "other" water bodies indexing out of range.
=> Crash Fixes

ipad/Utilities/API/APIRequest.swift, ipad/Utilities/Core/UI/Banner/Banner.swift
Increased timeout limit from 20 to 300 seconds for the next few weeks while openshift slowness is resolved.
=> Fix timeout bug

ipad/Models/Waterfract Inspection/WatercraftInspectionModel.swift, ipad/Services/CodeTableService.swift
Added inspection time to network request for inspection. Changed loading verbiage.
=> Add inspection time to request

Podfile, ipad.xcodeproj/project.pbxproj, ipad/Constants/AppRemoteAPIConst.swift, ipad/Constants/KeycloakConstants.swift, ipad/Services/AuthenticationService.swift
* SSO Pod updated to a [Gold-updated fork](https://github.com/Christopher-walsh22/InspectMusclesSSO) that includes PKCE verification
* Point to standard Gold realm and URLs
=> update to keycloak gold, use PKCE Pod

.github/workflows/main.yaml
- Tweak to project name in GitHub Actions for auto-signing and provisioning certs
=> [FEATURE][INSPECT-250]** Add App Store Connect certificate/provisioning to GitHub Actions (3)

.github/workflows/main.yaml
- Tweak to project name in GitHub Actions for auto-signing and provisioning certs
=> [FEATURE][INSPECT-250]** Add App Store Connect certificate/provisioning to GitHub Actions (4)

.github/workflows/main.yaml
- Tweak to project name in GitHub Actions for auto-signing and provisioning certs
=> [FEATURE][INSPECT-250]** Add App Store Connect certificate/provisioning to GitHub Actions (5)

ipad.xcodeproj/project.pbxproj
- Tweak to provisioning profile certificate
=> [FEATURE][INSPECT-250]** Add App Store Connect certificate/provisioning to GitHub Actions (6)

options.plist
- Tweak to uuid for the export action in GitHub Actions
=> [FEATURE][INSPECT-250]** Add App Store Connect certificate/provisioning to GitHub Actions (7)

exportOptions.plist
- Update provisioning name in exportOptions.plist
=> [FEATURE][INSPECT-250]** Add App Store Connect certificate/provisioning to GitHub Actions (9)

ipad.xcodeproj/project.pbxproj
- Increment build number for upload to App Store Connect
=> [FEATURE][INSPECT-250]** Add GitHub Actions to upload to App Store Connect (2)

ipad/Constants/StringConstants.swift, ipad/Database/Storage.swift, ipad/Models/Shift/Form Fields/ShiftFormHelper.swift, ipad/Models/Shift/ShiftModel.swift, ipad/ViewControllers/Shift/ShiftViewController.swift, ipad/Views/Form/Input Cells/Date Input/DateInputCollectionViewCell.swift, ipad/Views/Form/Input Cells/InputItem.swift, ipad/Views/New Shift Modal/NewShiftModal.swift
- Added Shift Start Date field to new Shifts for retro shift logging
- Fixed DateInput object
- Added alert message for users when creating a shift that occurred in the past
- Fixed minor typos in documentation
=> [INSPECT-251] FEATURE** Inspection date is updatable

README.md
- Update the README to add additional information about setup, roles, and TestFlight
=> [TECH-DEBT][INSPECT-#272] - Update README for new role management and TestFlight info

ipad/Constants/AppRemoteAPIConst.swift
- Change environment from `.dev` to `.prod` for launch
=> [INSPECT] - move dev to prod for v2.7 launch

Podfile, ipad/Constants/AppRemoteAPIConst.swift
- Point app at dev environment instead of prod 
- Update Podfile to set a minimum build version that should remove some (all?) errors in the GitHub action
- Dealing with Github actions means some trial and error is needed
- This is an iterative process
=> [INSPECT-302] ACTIONS** Update minimum build target

.github/workflows/main.yaml
- Lower action image from `14` to `13-large`
=> [INSPECT-301] ACTIONS** change action runner to macos-13-large

.github/workflows/main.yaml
- { List all the changes made }
- { Include any screenshots necessary }
=> modify install commands for codemagic

.github/workflows/main.yaml
- { List all the changes made }
- { Include any screenshots necessary }
=> 'pip3' -> 'pip'

.github/workflows/main.yaml
- { List all the changes made }
- { Include any screenshots necessary }
=> [INSPECT-301] MAINT** remove 'python3 -m' from install

ipad.xcodeproj/project.pbxproj
- { List all the changes made }
- { Include any screenshots necessary }
=> Update version number

ipad/Constants/AppRemoteAPIConst.swift
- Set build target to production, to submit changes to App Store Connect
=> [N/A] Set target to production

ipad/AppDelegate.swift, ipad/Constants/AppRemoteAPIConst.swift, ipad/Constants/StringConstants.swift, ipad/Views/Input Modal/InputModal.swift
- Change drain plug question to Was the drain plug already removed when arrived at the inspection station?
- Change suggested function renaming from Xcode suggestion
- Text has been changed as shown at the bottom of the image below:
=> [INSPECT-320][REFACTOR] - Update Drainplug text and function names DEV REALM

exportOptions.plist, ipad.xcodeproj/project.pbxproj, options.plist
- Updated Provision Profile and cert renewal
=> [UPDATE][INSPECT-XXX] - Apple Cert and Provisioning Profile Update

.github/workflows/main.yaml, ipad.xcodeproj/project.pbxproj
=> [UPDATE][INSPECT-XXX] - Bump App Version Number 

ipad/Constants/AppRemoteAPIConst.swift
- Change RemoteENV to prod for App Store deployment
=> [INSPECT-322][N/A] - Set app to prod environment for app store deployment

ipad/Constants/AppRemoteAPIConst.swift, ipad/Constants/StringConstants.swift, ipad/Database/Storage.swift, ipad/Models/Shift/Form Fields/ShiftFormHelper.swift, ipad/Models/Shift/ShiftModel.swift, ipad/ViewControllers/Shift/ShiftViewController.swift, ipad/Views/Form/Input Cells/InputItem.swift, ipad/Views/New Shift Modal/NewShiftModal.swift
- Added dynamic station comments field + validation for specific stations
- Adjusted form sizing and layout for shift start
- Renamed typo variables
- Removed debug code
=> [INSPECT-337][FEATURE] - Added updated station names and station comments text, with validation (DEV)

.github/workflows/main.yaml, ipad.xcodeproj/project.pbxproj, ipad/Database/Storage.swift
- Simple PR to update version number and put a limit on the station comments
=> [INSPECT-XXX][UPDATE] - Update version number and add station comments char limit

.github/workflows/main.yaml, ipad.xcodeproj/project.pbxproj, ipad/ViewControllers/Watercraft Inspections/WatercraftInspectionViewController.swift
- when first drainplug field toggled to false, second will also be false in all scenarios (confirmed in database)
- updated emojis for a cleaner ui experience
=> [INSPECT-333][FEATURE] feat: updated conditional field about drain plugs

.github/workflows/pr-notification.yaml
- Workflow attempt to add PR notifications to Teams
=> [INSPECT-XXX][FEATURE] Added Microsoft Teams PR notification

.github/workflows/main.yaml
=> [INSPECT-XXX][HOTFIX]: updated github workflow upload-artifact

.github/workflows/main.yaml, ipad.xcodeproj/project.pbxproj, ipad/ViewControllers/Watercraft Inspections/WatercraftInspectionViewController.swift
- fixed bug where dropdown was double populating in the watercraft details section of an inspection
=> [INSPECT-361][FIX]: Dropdown Bug Fix Watercraft Details

ipad/Constants/AppRemoteAPIConst.swift
=> [INSPECT-360][CI]: Push to Prod

.github/workflows/main.yaml, ipad.xcodeproj/project.pbxproj, ipad/Constants/AppRemoteAPIConst.swift, ipad/ViewControllers/Shift/ShiftViewController.swift
- Quick bug fix to correct validation when submitting a shift
=> [INSPECT-354][FIX] DaysOutOfWater Validation

.github/workflows/main.yaml, ipad.xcodeproj/project.pbxproj, ipad/Models/Watercraft Inspection/WatercraftInspectionModel.swift, ipad/ViewControllers/Shift/ShiftViewController.swift
- Set DaysOutOfWater to N/A if selected as Commercial Manufacturer.
=> [INSPECT-XXX][FIX]: DaysOutOfWater Bug Fix Part II

ipad/Constants/AppRemoteAPIConst.swift
=> [INSPECT-XXX][CI]: Push to Prod

.github/workflows/main.yaml
=> xcode Version Adjust for SDK
